### ISSUE TITLE
Crash in OpenCL

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#126]
Happened once, but let's keep an eye on it.
It was pr87, but pr87 did not change any logic in opencl (except a really big bug).

https://ghostbin.com/paste/8oqes

```
bestmove e2e4
ASAN:DEADLYSIGNAL
=================================================================
==42381==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fffc60ae457 bp 0x700006f6bbe0 sp 0x700006f6bbd0 T5)
==42381==The signal is caused by a READ memory access.
==42381==Hint: address points to the zero page.
    #0 0x7fffc60ae456  (GeForceGLDriver:x86_64+0x2ff456)
    #1 0x7fffc60ac9e3  (GeForceGLDriver:x86_64+0x2fd9e3)
    #2 0x7fffd8502a82 in gldDestroyQueue (libGPUSupportMercury.dylib:x86_64+0x2a82)
    #3 0x7fffcec05783  (OpenCL:x86_64+0x6783)
    #4 0x7fffcec057a9  (OpenCL:x86_64+0x67a9)
    #5 0x7fffcec212be in clReleaseCommandQueue (OpenCL:x86_64+0x222be)
    #6 0x105baf354 in cl::detail::ReferenceHandler<_cl_command_queue*>::release(_cl_command_queue*) cl2.hpp:1534
    #7 0x105baf31a in cl::detail::Wrapper<_cl_command_queue*>::release() const cl2.hpp:1724
    #8 0x105baf270 in cl::detail::Wrapper<_cl_command_queue*>::~Wrapper() cl2.hpp:1656
    #9 0x105baf214 in cl::CommandQueue::~CommandQueue() cl2.hpp:6620
    #10 0x105baea64 in cl::CommandQueue::~CommandQueue() cl2.hpp:6620
    #11 0x105c0f502 in ThreadData::~ThreadData() OpenCL.h:61
    #12 0x105be78e4 in ThreadData::~ThreadData() OpenCL.h:61
    #13 0x7fffdffbe82a in tlv_finalize (libdyld.dylib:x86_64+0x382a)
    #14 0x7fffe01db354 in _pthread_tsd_cleanup (libsystem_pthread.dylib:x86_64+0x5354)
    #15 0x7fffe01db0d8 in _pthread_exit (libsystem_pthread.dylib:x86_64+0x50d8)
    #16 0x7fffe01d9945 in _pthread_body (libsystem_pthread.dylib:x86_64+0x3945)
    #17 0x7fffe01d9886 in _pthread_start (libsystem_pthread.dylib:x86_64+0x3886)
    #18 0x7fffe01d908c in thread_start (libsystem_pthread.dylib:x86_64+0x308c)
```

**Comment by frpays** [comment]
Maybe we should start gathering them.
Maybe it's a bad driver, maybe it's a bad hardware.
But at least, if something starts to show up, we can figure it out.

**Comment by borg323** [comment]
In discord, during testing of the windows OpenCL builds, I was told: "After i stop analysis then when i try to analyze again it crashes.
the same of course with games. it can't play a game, as in the 2nd move it crashes.
same with lczero.exe". 

This was using:
```
Platform version: OpenCL 2.1 AMD-APP (2580.6)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.
Device ID:     0
Device name:   Baffin
Device type:   GPU
Device vendor: Advanced Micro Devices, Inc.
Device driver: 2580.6
Device speed:  1210 MHz
Device cores:  14 CU
Device score:  1121
```

**Comment by frpays** [comment]
https://pastebin.com/jR1tNUiv

**Comment by frpays** [comment]
https://pastebin.com/wkzG40eC

**Comment by mooskagh** [comment]
Not reproducible recently? Closing.
(if it's reproducible, feel free to reopen)
